-keepnames class androidx.navigation.fragment.NavHostFragment {}
-keepnames class androidx.fragment.app.FragmentContainerView {}
-keep class de.janniskilian.basket.feature.settings.PreferenceFragment {}
